// Code generated by envgen. DO NOT EDIT.

package minimal

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := ReloadConfig(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	return loadConfig(cfg, env.Snapshot())
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("8080")
			if err != nil {
				env.AppendParse(&errs, "Port", key, "8080", err)
			} else {
				cfg.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Port", key, raw, err)
			} else {
				cfg.Port = v
			}
		}
	}
	{
		key := "DEBUG"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Debug", key, raw, err)
			} else {
				cfg.Debug = v
			}
		}
	}
	{
		key := "HOST"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.Host = "localhost"
		} else {
			cfg.Host = raw
		}
	}
	return env.NewError(errs)
}
