package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/gopherust-io/env/internal/tag"
)

type Options struct {
	Package  string
	TypeName string
	Module   string
	Fields   []tag.Field
}

func Generate(opts Options) ([]byte, error) {
	if opts.Module == "" {
		opts.Module = "github.com/gopherust-io/env"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by envgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	b.WriteString("import (\n")
	b.WriteString("\tenv \"" + opts.Module + "\"\n")
	if needsTimeImport(opts.Fields) {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "func Load%s() (%s, error) {\n", opts.TypeName, opts.TypeName)
	b.WriteString("\tvar cfg " + opts.TypeName + "\n")
	fmt.Fprintf(&b, "\tif err := Reload%s(&cfg); err != nil {\n", opts.TypeName)
	b.WriteString("\t\treturn cfg, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn cfg, nil\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "func Reload%s(cfg *%s) error {\n", opts.TypeName, opts.TypeName)
	b.WriteString("\tenv.Reload()\n")
	fmt.Fprintf(&b, "\treturn load%s(cfg, env.Snapshot())\n", opts.TypeName)
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "func MustReload%s(cfg *%s) {\n", opts.TypeName, opts.TypeName)
	fmt.Fprintf(&b, "\tif err := Reload%s(cfg); err != nil {\n", opts.TypeName)
	b.WriteString("\t\tpanic(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "func Load%sFrom(snap *env.EnvSnapshot) (%s, error) {\n", opts.TypeName, opts.TypeName)
	fmt.Fprintf(&b, "\tvar cfg %s\n", opts.TypeName)
	fmt.Fprintf(&b, "\tif err := load%s(&cfg, snap); err != nil {\n", opts.TypeName)
	b.WriteString("\t\treturn cfg, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn cfg, nil\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "func MustLoad%s() %s {\n", opts.TypeName, opts.TypeName)
	fmt.Fprintf(&b, "\tcfg, err := Load%s()\n", opts.TypeName)
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tpanic(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn cfg\n")
	b.WriteString("}\n\n")

	if hasSensitive(opts.Fields) {
		emitMasked(&b, opts)
	}

	fmt.Fprintf(&b, "func load%s(cfg *%s, snap *env.EnvSnapshot) error {\n", opts.TypeName, opts.TypeName)
	b.WriteString("\tvar errs []env.FieldError\n")
	for _, f := range opts.Fields {
		emitFieldLoad(&b, f, "cfg", opts.TypeName)
	}
	b.WriteString("\treturn env.NewError(errs)\n")
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), err
	}
	return formatted, nil
}

func emitMasked(b *bytes.Buffer, opts Options) {
	fmt.Fprintf(b, "func (c %s) Masked() %s {\n", opts.TypeName, opts.TypeName)
	b.WriteString("\tout := c\n")
	emitMaskedFields(b, opts.Fields, "out")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n\n")
}

func emitMaskedFields(b *bytes.Buffer, fields []tag.Field, target string) {
	for _, f := range fields {
		if f.IsNested {
			for _, child := range f.Children {
				if child.Sensitive {
					fmt.Fprintf(b, "\t%s.%s.%s = env.SensitiveMask\n", target, f.Name, child.Name)
				}
			}
			continue
		}
		if f.Sensitive {
			fmt.Fprintf(b, "\t%s.%s = env.SensitiveMask\n", target, f.Name)
		}
	}
}

func emitFieldLoad(b *bytes.Buffer, f tag.Field, target, rootType string) {
	if f.IsNested {
		for _, child := range f.Children {
			emitLeafLoad(b, child, target+"."+f.Name, f.Prefix)
		}
		return
	}
	emitLeafLoad(b, f, target, f.Prefix)
}

func emitLeafLoad(b *bytes.Buffer, f tag.Field, target, prefix string) {
	key := prefix + f.EnvKey
	fieldLabel := f.FieldPath
	if fieldLabel == "" {
		fieldLabel = f.Name
	}

	fmt.Fprintf(b, "\t{\n")
	fmt.Fprintf(b, "\t\tkey := %q\n", key)
	b.WriteString("\t\traw, ok := snap.Lookup(key)\n")
	b.WriteString("\t\tif !ok || raw == \"\" {\n")
	if f.Required && f.Default == "" {
		fmt.Fprintf(b, "\t\t\tenv.AppendRequired(&errs, %q, key)\n", fieldLabel)
	} else if f.Default != "" {
		emitDefaultAssign(b, f, target)
	} else if f.IsPointer {
		fmt.Fprintf(b, "\t\t\t%s.%s = nil\n", target, f.Name)
	}
	b.WriteString("\t\t} else {\n")

	if f.Expand {
		b.WriteString("\t\t\traw = env.Expand(raw, snap)\n")
	}

	if f.Unmarshal {
		fmt.Fprintf(b, "\t\t\tif err := %s.%s.UnmarshalEnv(key, raw); err != nil {\n", target, f.Name)
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t}\n")
	} else {
		emitParseAssign(b, f, target, fieldLabel)
	}
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
}

func emitDefaultAssign(b *bytes.Buffer, f tag.Field, target string) {
	val := f.Default
	switch {
	case f.GoType == "string":
		if f.Expand {
			fmt.Fprintf(b, "\t\t\t%s.%s = env.Expand(%q, snap)\n", target, f.Name, val)
		} else {
			fmt.Fprintf(b, "\t\t\t%s.%s = %q\n", target, f.Name, val)
		}
	case f.GoType == "bool":
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseBool(%q)\n", val)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.GoType == "time.Duration":
		if f.Expand {
			fmt.Fprintf(b, "\t\t\tv, err := env.ParseDuration(env.Expand(%q, snap))\n", val)
		} else {
			fmt.Fprintf(b, "\t\t\tv, err := env.ParseDuration(%q)\n", val)
		}
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.GoType == "time.Time":
		layout := f.Layout
		if layout == "" {
			layout = "2006-01-02T15:04:05Z07:00"
		}
		if f.Expand {
			fmt.Fprintf(b, "\t\t\tv, err := env.ParseTime(env.Expand(%q, snap), %q)\n", val, layout)
		} else {
			fmt.Fprintf(b, "\t\t\tv, err := env.ParseTime(%q, %q)\n", val, layout)
		}
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case strings.HasPrefix(f.GoType, "int"), strings.HasPrefix(f.GoType, "uint"), strings.HasPrefix(f.GoType, "float"):
		parser := parseFunc(f.GoType)
		fmt.Fprintf(b, "\t\t\tv, err := env.%s(%q)\n", parser, val)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsSlice && f.SliceElem == "string":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseStringSlice(%q, %q)\n", val, sep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsSlice && f.SliceElem == "int":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseIntSlice(%q, %q)\n", val, sep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsMap && f.MapKey == "string" && f.MapValue == "string":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		kvSep := f.KvSep
		if kvSep == "" {
			kvSep = ":"
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseStringMap(%q, %q, %q)\n", val, sep, kvSep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, %q, err)\n", f.FieldPath, val)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	default:
		fmt.Fprintf(b, "\t\t\t%s.%s = %q\n", target, f.Name, val)
	}
}

func emitParseAssign(b *bytes.Buffer, f tag.Field, target, fieldLabel string) {
	switch {
	case f.GoType == "string":
		fmt.Fprintf(b, "\t\t\t%s.%s = raw\n", target, f.Name)
	case f.GoType == "bool":
		b.WriteString("\t\t\tv, err := env.ParseBool(raw)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.GoType == "time.Duration":
		b.WriteString("\t\t\tv, err := env.ParseDuration(raw)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.GoType == "time.Time":
		layout := f.Layout
		if layout == "" {
			layout = "2006-01-02T15:04:05Z07:00"
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseTime(raw, %q)\n", layout)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsSlice && f.SliceElem == "string":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseStringSlice(raw, %q)\n", sep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsSlice && f.SliceElem == "int":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseIntSlice(raw, %q)\n", sep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsMap && f.MapKey == "string" && f.MapValue == "string":
		sep := f.Sep
		if sep == "" {
			sep = ","
		}
		kvSep := f.KvSep
		if kvSep == "" {
			kvSep = ":"
		}
		fmt.Fprintf(b, "\t\t\tv, err := env.ParseStringMap(raw, %q, %q)\n", sep, kvSep)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	case f.IsPointer && strings.TrimPrefix(f.GoType, "*") == "string":
		b.WriteString("\t\t\tv := raw\n")
		fmt.Fprintf(b, "\t\t\t%s.%s = &v\n", target, f.Name)
	default:
		parser := parseFunc(strings.TrimPrefix(f.GoType, "*"))
		fmt.Fprintf(b, "\t\t\tv, err := env.%s(raw)\n", parser)
		b.WriteString("\t\t\tif err != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tenv.AppendParse(&errs, %q, key, raw, err)\n", fieldLabel)
		b.WriteString("\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\t%s.%s = v\n", target, f.Name)
		b.WriteString("\t\t\t}\n")
	}
}

func parseFunc(goType string) string {
	switch goType {
	case "int":
		return "ParseInt"
	case "int8":
		return "ParseInt8"
	case "int16":
		return "ParseInt16"
	case "int32":
		return "ParseInt32"
	case "int64":
		return "ParseInt64"
	case "uint":
		return "ParseUint"
	case "uint8":
		return "ParseUint8"
	case "uint16":
		return "ParseUint16"
	case "uint32":
		return "ParseUint32"
	case "uint64":
		return "ParseUint64"
	case "float32":
		return "ParseFloat32"
	case "float64":
		return "ParseFloat64"
	default:
		return "ParseInt"
	}
}

func needsTimeImport(fields []tag.Field) bool {
	for _, f := range fields {
		if f.GoType == "time.Duration" {
			return false
		}
		if f.IsNested {
			if needsTimeImport(f.Children) {
				return true
			}
		}
	}
	return false
}

func hasSensitive(fields []tag.Field) bool {
	for _, f := range fields {
		if f.Sensitive {
			return true
		}
		if f.IsNested && hasSensitive(f.Children) {
			return true
		}
	}
	return false
}
