// Code generated by envgen. DO NOT EDIT.

package crosspkg

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := ReloadConfig(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	return loadConfig(cfg, env.Snapshot())
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func (c Config) Masked() Config {
	out := c
	out.DB.Password = env.SensitiveMask
	return out
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "DB_HOST"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "DB.Host", key)
		} else {
			cfg.DB.Host = raw
		}
	}
	{
		key := "DB_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.DB.Password = raw
		}
	}
	{
		key := "DB_PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("5432")
			if err != nil {
				env.AppendParse(&errs, "DB.Port", key, "5432", err)
			} else {
				cfg.DB.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.Port", key, raw, err)
			} else {
				cfg.DB.Port = v
			}
		}
	}
	{
		key := "PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("8080")
			if err != nil {
				env.AppendParse(&errs, "Port", key, "8080", err)
			} else {
				cfg.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Port", key, raw, err)
			} else {
				cfg.Port = v
			}
		}
	}
	return env.NewError(errs)
}
