// Code generated by envgen. DO NOT EDIT.

package basic

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	snap := env.Snapshot()
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func (c Config) Masked() Config {
	out := c
	out.DB.Password = env.SensitiveMask
	return out
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "STARTED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			v, err := env.ParseTime(raw, "2006-01-02")
			if err != nil {
				env.AppendParse(&errs, "Started", key, raw, err)
			} else {
				cfg.Started = v
			}
		}
	}
	{
		key := "LABELS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			v, err := env.ParseStringMap(raw, ",", ":")
			if err != nil {
				env.AppendParse(&errs, "Labels", key, raw, err)
			} else {
				cfg.Labels = v
			}
		}
	}
	{
		key := "DB_HOST"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "DB.Host", key)
		} else {
			cfg.DB.Host = raw
		}
	}
	{
		key := "DB_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.DB.Password = raw
		}
	}
	{
		key := "DB_PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("5432")
			if err != nil {
				env.AppendParse(&errs, "DB.Port", key, "5432", err)
			} else {
				cfg.DB.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.Port", key, raw, err)
			} else {
				cfg.DB.Port = v
			}
		}
	}
	{
		key := "BASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.BaseURL = env.Expand("${NATS_URL}/api", snap)
		} else {
			raw = env.Expand(raw, snap)
			cfg.BaseURL = raw
		}
	}
	{
		key := "TAGS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			v, err := env.ParseStringSlice(raw, ",")
			if err != nil {
				env.AppendParse(&errs, "Tags", key, raw, err)
			} else {
				cfg.Tags = v
			}
		}
	}
	{
		key := "PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("8080")
			if err != nil {
				env.AppendParse(&errs, "Port", key, "8080", err)
			} else {
				cfg.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Port", key, raw, err)
			} else {
				cfg.Port = v
			}
		}
	}
	{
		key := "TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "Timeout", key, "10s", err)
			} else {
				cfg.Timeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Timeout", key, raw, err)
			} else {
				cfg.Timeout = v
			}
		}
	}
	{
		key := "DEBUG"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Debug", key, raw, err)
			} else {
				cfg.Debug = v
			}
		}
	}
	return env.NewError(errs)
}
